#!/bin/bash

while [ true ]; do
	if [[ $(ping -c 1 `hostname`.local) ]]; then
		echo `date` > /tmp/avahi-log.txt
		echo "GOOD" >> /tmp/avahi-log.txt
	else
		echo `date` > /tmp/avahi-log.txt
		echo "FAIL" >> /tmp/avahi-log.txt
	fi

	if [[ `grep -w "GOOD" "/tmp/avahi-log.txt"` ]]; then
		sleep 1800s;
	else
		service avahi-daemon restart;
	fi
done
