#!/bin/bash

CHECK=$(echo `date` > /tmp/avahi-log.txt && sleep 20s && ping `hostname`.local -w 3 >> /tmp/avahi-log.txt && sleep 1800s)

while [ true ]; do
	if [ -e /usr/local/sbin/avahi-check ]; then
		$CHECK;
	else
		service avahi-daemon restart;
	fi
done
