#!/bin/bash

install(){
sudo apt update; sudo apt upgrade -y; sudo apt install -y avahi-utils
sudo wget https://raw.githubusercontent.com/pyavitz/scripts/master/avahi-monitor -P /usr/local/sbin/
sudo chmod +x `command -v avahi-monitor`

sudo tee /etc/systemd/system/avahi-monitor.service <<EOF
[Unit]
Description=Avahi Monitor
ConditionPathExists=/usr/local/sbin/avahi-monitor

[Service]
ExecStart=/usr/local/sbin/avahi-monitor &>/dev/null
Type=simple
#RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl enable avahi-check
sudo reboot
}

while [ true ]; do
	if [[ $(ping -c 1 `hostname`.local) ]]; then
		echo `date` > /tmp/avahi-status.log;
		echo 'STATUS="ok"' >> /tmp/avahi-status.log;
	else
		echo `date` > /tmp/avahi-status.log;
		echo 'STATUS="fail"' >> /tmp/avahi-status.log;
	fi
	sleep 2s
	if [[ `grep -w 'STATUS="ok"' "/tmp/avahi-status.log"` ]]; then
		sleep 1800s;
	else
		service avahi-daemon restart;
	fi
done
