#!/bin/bash
# depends on nmount
#
# place in /etc/rc.local
# if [ -e /usr/local/bin/cmount ]; then
# 	sleep 20s
# 	cmount;
# fi

CHECK="/mnt/camera/check"

mount_cam(){
if [ -e /usr/local/bin/nmount ]; then
	nmount -m;
fi
}

mount_check(){
while [ true ]; do
	if [ -e $CHECK ]; then
		sleep 1800s;
	fi
done
}

while [ true ]; do
	if [ -e $CHECK ]; then
		mount_check;
	else
		nmount -u > /dev/null 2>&1
		sudo rm -fdr /mnt/camera/*
		sleep 2s
		mount_cam
		sleep 10s
		mount_check;
	fi
done
