#!/usr/bin/env bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DOWNLOAD="aria2c -c --download-result=hide --console-log-level=error --disable-ipv6=true --summary-interval=0 --show-files=false"
PATCHES="https://raw.githubusercontent.com/pyavitz/rpi-img-builder/master/files/debian/patches/"
CHANGELOG="https://raw.githubusercontent.com/raspberrypi/rpi-eeprom/debian/bullseye/debian/changelog"
URL="https://archive.raspberrypi.org/debian/pool/main/r/rpi-eeprom/"
RED="\e[1;31m"
GRN="\e[1;32m"
PNK="\e[1;35m"
WHT="\e[1;37m"
YLW="\e[1;33m"
FIN="\e[0m"

echo_bdone(){
echo -e "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
}

echo_nok(){
echo -e -n "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_fail(){
echo -n -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
}

current(){
version=$(apt-cache show rpi-eeprom | grep -Po '(?<=Version:)[^;]+' | head -1)
echo "   CURRENT:$version"
}

latest(){
version=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==1) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
echo "   AVAILABLE: $version"
}

error(){
echo -e ${RED}Something went wrong${FIN}? ${RED}Please report error${FIN}.
}

update(){
sudo mv -f /usr/local/bin/deb-eeprom /usr/local/bin/deb-eeprom.orig
sudo mv -f /usr/local/bin/write2usb /usr/local/bin/write2usb.orig
sudo wget -cq https://github.com/pyavitz/scripts/raw/master/deb-eeprom -P /usr/local/bin
sudo wget -cq https://github.com/pyavitz/scripts/raw/master/write2usb -P /usr/local/bin
sudo chmod +x /usr/local/bin/deb-eeprom
sudo chmod +x /usr/local/bin/write2usb
if [ -e /usr/local/bin/deb-eeprom ]; then sudo rm -f /usr/local/bin/deb-eeprom.orig; else sudo mv -f /usr/local/bin/deb-eeprom.orig /usr/local/bin/deb-eeprom; fi
if [ -e /usr/local/bin/write2usb ]; then sudo rm -f /usr/local/bin/write2usb.orig; else sudo mv -f /usr/local/bin/write2usb.orig /usr/local/bin/write2usb; fi
deb-eeprom -h
}

cleaning(){
cd /home/$USER
rm -fdr /home/$USER/.build/eeprom
}

checking(){
echo -e "${WHT}Checking for updates${FIN} ..."
sudo apt update
sudo apt upgrade -y
sudo apt install help2man rsync pciutils aria2 -y
if [ -e /home/$USER/.eeprom ]; then rm -f /home/$USER/.eeprom; fi
if ls /home/$USER/.build/eeprom > /dev/null 2>&1; then sudo rm -fdr /home/$USER/.build/eeprom; fi
if ls /usr/local/src/*.patch > /dev/null 2>&1; then sudo rm -f /usr/local/src/*.patch; fi
if [ -e /usr/local/bin/deb-eeprom-update ]; then sudo rm -f /usr/local/bin/deb-eeprom-update; fi
}

builddir(){
echo && echo -n "Setup   "
sleep 1s
mkdir -p /home/$USER/.build/eeprom
cd /home/$USER/.build/eeprom && echo_nok
echo && echo -n "Patches "
wget -cq ${PATCHES}rpi-eeprom-control.patch
wget -cq ${PATCHES}rpi-eeprom-update.patch
if ls /home/$USER/.build/eeprom/{rpi-eeprom-control.patch,rpi-eeprom-update.patch} > /dev/null 2>&1; then
	echo_nok;
else
	echo_fail
	exit;
fi
}

find_eeprom(){
EEPROM_VERSION=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==1) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
if [[ `wget -S --spider ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	download_eeprom;
else
	finding_eeprom;
fi
}

finding_eeprom(){
EEPROM_VERSION=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==10) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
if [[ `wget -S --spider ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	download_eeprom;
else
	error
	cleaning
	exit;
fi
}

download_eeprom(){
echo
echo -e -n "${WHT}Searching${FIN} ..."
sleep 1s
${DOWNLOAD} ${URL}rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
${DOWNLOAD} ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz && echo_bdone
}

build_eeprom(){
echo
echo -e "${RED}Installing rpi-eeprom${FIN} ..."
tar xf rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz
tar xf rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
rm -f rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
mkdir -p debian/patches
mv rpi-eeprom-update.patch debian/patches/rpi-eeprom-update.patch 
echo rpi-eeprom-update.patch >> debian/patches/series
mv -f debian rpi-eeprom-${EEPROM_VERSION}/
mv rpi-eeprom-control.patch rpi-eeprom-${EEPROM_VERSION}/
cd rpi-eeprom-${EEPROM_VERSION}
patch -p1 < rpi-eeprom-control.patch
rm -f rpi-eeprom-control.patch
dpkg-buildpackage -us -nc -uc
cd ..
sudo dpkg -i *.deb
cd ..
echo -e "${RED}Done${FIN}."
cd /home/$USER
rm -fdr /home/$USER/.build/eeprom
echo
echo "Check for update - sudo rpi-eeprom-update"
echo "Update bootloader - sudo rpi-eeprom-update -a"
echo
}

rite2usb(){
sudo write2usb
}

upgrade_eeprom(){
checking
builddir
find_eeprom
build_eeprom
}

### CHECKS
internet_check(){
if [[ `command -v wget` ]]; then
	[[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]];
else
	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
		echo -e "${WHT}Installing missing depends${FIN}."
		sudo apt update
		sudo apt upgrade -y
		sudo apt install -y wget;
	else
		echo -e "This script requires an internet connection."
		exit;
	fi
fi
}

depends_check(){
if [[ `command -v aria2c` ]]; then :; else sudo apt update; sudo apt upgrade -y; sudo apt install -y aria2; fi
}

internet_check
depends_check
# Commands
if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

ECHO="false"

while getopts "uUwh" OPTION; do
        case $OPTION in

                U)
                        ECHO="upgrade"
                        ;;
                w)
                        ECHO="rite2usb"
                        ;;
                u)
                        ECHO="update"
                        ;;
                h)
                        echo -e "${RED}Raspberry Pi 4B EEPROM Helper Script${FIN}"
                        echo "Usage: deb-eeprom -h"
                        echo ""
                        current
                        latest
                        echo ""
                        echo "   -U       Upgrade eeprom package"
                        echo "   -w       Transfer to USB"
                        echo "   -u       Update script"
                        echo ""
                        exit 0
                        ;;

        esac
done

if [ $ECHO = "upgrade" ]; then
	upgrade_eeprom;
fi
if [ $ECHO = "rite2usb" ]; then
	rite2usb;
fi
if [ $ECHO = "update" ]; then
	update;
fi
