#!/usr/bin/env bash
# Description: get latest eeprom
# Destination: /usr/local/bin/deb-eeprom

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DOWNLOAD="aria2c -c --download-result=hide --console-log-level=error --disable-ipv6=true --summary-interval=0 --show-files=false"
PATCHES="https://raw.githubusercontent.com/pyavitz/rpi-img-builder/master/files/patches/"
CHANGELOG="https://raw.githubusercontent.com/raspberrypi/rpi-eeprom/debian/bookworm/debian/changelog"
URL="https://archive.raspberrypi.org/debian/pool/main/r/rpi-eeprom/"
RED="\e[0;31m"
GRN="\e[0;32m"
PNK="\e[0;35m"
TXT="\033[0m"
YLW="\e[0;33m"
FIN="\e[0m"

if [[ `command -v wget` ]]; then
	[[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]];
else
	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
		echo -e "${TXT}Installing missing depends${FIN}."
		sudo apt update
		sudo apt upgrade -y
		sudo apt install -y wget
	else
		echo -e "This script requires an internet connection."
		exit 0
	fi
fi

if [[ `command -v aria2c` ]]; then :; else sudo apt update; sudo apt upgrade -y; sudo apt install -y aria2; fi

echo_bdone(){
echo -e "${PNK}[${FIN}${GRN}done${FIN}${PNK}]${FIN}"
}

echo_nok(){
echo -e -n "${PNK}[${FIN}${GRN}ok${FIN}${PNK}]${FIN}"
}

echo_fail(){
echo -n -e "${PNK}[${FIN}${RED}failed${FIN}${PNK}]${FIN}"
}

current(){
version=$(apt-cache show rpi-eeprom | grep -Po '(?<=Version:)[^;]+' | head -1)
echo "   CURRENT:$version"
}

latest(){
version=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==1) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
echo "   AVAILABLE: $version"
}

error(){
echo ""
echo -e ${TXT}Something went wrong${FIN}? ${YLW}Please report error${FIN}.
}

update(){
if [[ `command -v deb-eeprom` ]]; then
	sudo mv -f /usr/local/bin/deb-eeprom /usr/local/bin/deb-eeprom.orig
	sudo wget -cq https://github.com/pyavitz/scripts/raw/master/deb-eeprom -P /usr/local/bin
	sudo chmod +x /usr/local/bin/deb-eeprom
	if [[ -f "/usr/local/bin/deb-eeprom" ]]; then
		sudo rm -f /usr/local/bin/deb-eeprom.orig
	else
		sudo mv -f /usr/local/bin/deb-eeprom.orig /usr/local/bin/deb-eeprom
	fi
fi
deb-eeprom
}

cleaning(){
cd /home/$USER
rm -fdr /home/$USER/.build/eeprom
}

checking(){
echo ""
echo -e "Checking for updates ..."
sudo apt update
sudo apt upgrade -y
sudo apt install help2man rsync pciutils aria2 -y
if [ -e /home/$USER/.eeprom ]; then rm -f /home/$USER/.eeprom; fi
if ls /home/$USER/.build/eeprom > /dev/null 2>&1; then sudo rm -fdr /home/$USER/.build/eeprom; fi
if ls /usr/local/src/*.patch > /dev/null 2>&1; then sudo rm -f /usr/local/src/*.patch; fi
if [ -e /usr/local/bin/deb-eeprom-update ]; then sudo rm -f /usr/local/bin/deb-eeprom-update; fi
}

builddir(){
echo ""
echo -en "Running setup "
sleep 1s
mkdir -p /home/$USER/.build/eeprom
cd /home/$USER/.build/eeprom
wget -cq ${PATCHES}rpi-eeprom-control
wget -cq ${PATCHES}rpi-eeprom-update.patch
if ls /home/$USER/.build/eeprom/{rpi-eeprom-control,rpi-eeprom-update.patch} > /dev/null 2>&1; then
	echo_bdone
else
	echo_fail
	exit 1
fi
}

find_eeprom(){
EEPROM_VERSION=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==1) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
if [[ `wget -S --spider ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	download_eeprom
else
	finding_eeprom
fi
}

finding_eeprom(){
EEPROM_VERSION=$(curl --silent -L ${CHANGELOG} | awk '{if (NR==10) {print substr($2, 1, length($2)-3)}}' | sed 's/[()]//g')
if [[ `wget -S --spider ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	download_eeprom
else
	error
	cleaning
	exit 1
fi
}

download_eeprom(){
echo ""
echo -en "Searching ..."
sleep 1s
${DOWNLOAD} ${URL}rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
${DOWNLOAD} ${URL}rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz && echo_bdone
}

build_eeprom(){
echo ""
echo -e "Updating rpi-eeprom ..."
tar xf rpi-eeprom_${EEPROM_VERSION}.orig.tar.gz
tar xf rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
rm -f rpi-eeprom_${EEPROM_VERSION}-1.debian.tar.xz
mkdir -p debian/patches
mv rpi-eeprom-update.patch debian/patches/rpi-eeprom-update.patch 
echo rpi-eeprom-update.patch >> debian/patches/series
rm -f debian/control; mv -f rpi-eeprom-control debian/control
mv -f debian rpi-eeprom-${EEPROM_VERSION}/
mv rpi-eeprom-control.patch rpi-eeprom-${EEPROM_VERSION}/
cd rpi-eeprom-${EEPROM_VERSION}
dpkg-buildpackage -us -nc -uc
cd ..
sudo dpkg -i *.deb
cd ..
echo -e "Done."
cd /home/$USER
rm -fdr /home/$USER/.build/eeprom
echo
echo "Check for update - sudo rpi-eeprom-update"
echo "Update bootloader - sudo rpi-eeprom-update -a"
echo
}

upgrade(){
checking; builddir; find_eeprom; build_eeprom
}

if [ $# -eq 0 ]; then
	echo ""
	current
	latest
	echo ""
	>&2 echo -e "Arguments: upgrade update"
	exit 1
fi
case $1 in
	upgrade|update)
	;;
	*)
	echo -e "Arguments: upgrade update" >&2
	exit 1
esac

EEPROM=`echo $1`
$EEPROM

exit 0
