#!/bin/bash

depends_check(){
if [[ `command -v wget dtc` ]]; then
	:;
else
	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
		echo -e "Installing missing depends."
		sudo apt update
		sudo apt upgrade -y
		sudo apt install -y wget device-tree-compiler;
	else
		echo ""
		echo -e "This script requires an internet connection."
		exit;
	fi
fi
}

internet_check(){
if [[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	:;
else
	echo -e "This script requires an internet connection."
	exit;
fi
}

disable_hdmi_audio_overlay(){
if [ -e /boot/overlays/disable-hdmi-audio.dtbo ]; then
	sudo rm -f /boot/overlays/disable-hdmi-audio.dtbo;
else
	:;
fi
cat << '_EOF_' > disable-hdmi-audio.dts
/dts-v1/;
/plugin/;
/ {
  compatible = "brcm,bcm2835";
  fragment@0 {
    target = <&audio>;
    __overlay__ {
      brcm,disable-hdmi = <1>;
    };
  };
};
_EOF_
sudo dtc -I dts -O dtb -o /boot/overlays/disable-hdmi-audio.dtbo disable-hdmi-audio.dts
rm -f disable-hdmi-audio.dts
}

depends_check
internet_check
disable_hdmi_audio_overlay
echo
if [ -e /boot/overlays/disable-hdmi-audio.dtbo ]; then
	echo -e "Results:"
	ls /boot/overlays/disable-hdmi-audio.dtbo;
else
	:;
fi
