#!/bin/bash

internet_check(){
if [[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
	:;
else
	echo -e "This script requires an internet connection."
	exit;
fi
}

dtc_check(){
if [ -e /usr/bin/dtc ]; then :; else sudo apt update && sudo apt install device-tree-compiler -y; fi
}

disable_hdmi_audio_overlay(){
if [ -e /boot/overlays/disable-hdmi-audio.dtbo ]; then sudo rm -f /boot/overlays/disable-hdmi-audio.dtbo; else :; fi
cat << '_EOF_' > disable-hdmi-audio.dts
/dts-v1/;
/plugin/;
/ {
  compatible = "brcm,bcm2835";
  fragment@0 {
    target = <&audio>;
    __overlay__ {
      brcm,disable-hdmi = <1>;
    };
  };
};
_EOF_
sudo dtc -I dts -O dtb -o /boot/overlays/disable-hdmi-audio.dtbo disable-hdmi-audio.dts
rm -f disable-hdmi-audio.dts
}

internet_check
dtc_check
disable_hdmi_audio_overlay
echo
if [ -e /boot/overlays/disable-hdmi-audio.dtbo ]; then
	echo -e "Results:"
	ls /boot/overlays/disable-hdmi-audio.dtbo;
else
	:;
fi
