#!/bin/bash

# host machine
DISTRO=`cat /etc/os-release | grep -w NAME | sed 's/NAME=//g' | sed 's/"//g' | sed 's/ GNU\/Linux//g'`
CODENAME=`cat /etc/os-release | grep -w "VERSION_CODENAME" | sed 's/VERSION_CODENAME=//g'`
ARCH=`uname -m`

# manual
NODE="/dev/sda1"
POINT="/mnt/external"

if [ "$USER" != "root" ]; then
	echo "Please run this as root or with sudo privileges."
	exit 0
fi

if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "muh" OPTION; do
	case $OPTION in
		m)
			if [[ -e "${NODE}" ]] && [[ -e "${POINT}" ]]; then
				mount ${NODE} ${POINT}
				if [[ "$DISTRO" == "Debian" || "$DISTRO" == "Kali" || "$DISTRO" == "Raspbian" || "$DISTRO" == "Ubuntu" ]]; then
					systemctl daemon-reload
				fi
			else
				mkdir -p ${POINT}
				sleep .75
				mount ${NODE} ${POINT}
				if [[ "$DISTRO" == "Debian" || "$DISTRO" == "Kali" || "$DISTRO" == "Raspbian" || "$DISTRO" == "Ubuntu" ]]; then
					systemctl daemon-reload
				fi
			fi
			;;
		u)
			if [[ -e "${NODE}" ]] && [[ -e "${POINT}" ]]; then
				umount ${POINT}
			fi
			;;
		h)
			echo ""
			echo -e "Mount Drive"
			echo ""
			echo -e "\t-m\tMount"
			echo -e "\t-u\tUnmount"
			echo ""
			echo -e "\t-h\tHelp"
			echo ""
			exit 0
			;;
	esac
done

exit 0
