#!/usr/bin/env bash
source /etc/opt/board.txt
POINT="55000"
DIR="/usr/local/bin"
TXT="\033[0m"
FIN="\e[0m"

odroidn2(){
if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp" ]]; then
	echo $POINT | sudo tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp;
else
	echo -e "You are missing trip_point_4_temp?";
	exit 0;
fi
}

odroidxu4(){
TZONE0="/sys/devices/virtual/thermal/thermal_zone0/trip_point_0_temp"
TZONE1="/sys/devices/virtual/thermal/thermal_zone1/trip_point_0_temp"
TZONE2="/sys/devices/virtual/thermal/thermal_zone2/trip_point_0_temp"
TZONE3="/sys/devices/virtual/thermal/thermal_zone3/trip_point_0_temp"
if [[ -f "$TZONE0" ]] && [[ -f "$TZONE1" ]] && [[ -f "$TZONE2" ]] && [[ -f "$TZONE3" ]]; then
	echo $POINT | sudo tee /sys/devices/virtual/thermal/thermal_zone{0,1,2,3}/trip_point_0_temp;
else
	echo -e "You are missing a trip point?";
	exit 0;
fi
}

if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "6543rumh" OPTION; do
	case $OPTION in

	6)
		sudo sed -i "3s/.*/POINT="'"65000"'"/" $DIR/fan-ctrl
		fan-ctrl -r
		;;
	5)
		sudo sed -i "3s/.*/POINT="'"55000"'"/" $DIR/fan-ctrl
		fan-ctrl -r
		;;
	4)
		sudo sed -i "3s/.*/POINT="'"45000"'"/" $DIR/fan-ctrl
		fan-ctrl -r
		;;
	3)
		sudo sed -i "3s/.*/POINT="'"35000"'"/" $DIR/fan-ctrl
		fan-ctrl -r
		;;
	r)
		if [[ "$BOARD" == "odroidn2" ]] || [[ "$BOARD" == "odroidn2plus" ]]; then
			odroidn2;
		fi
		if [[ "$BOARD" == "odroidxu4" ]]; then
			odroidxu4;
		fi
		;;
	u)
		if [[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
			if [ -f `command -v fan-ctrl` ]; then
				sudo mv -f $DIR/fan-ctrl $DIR/fan-ctrl.orig;
			fi
			sudo wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/fan-ctrl -P $DIR/
			sudo chmod +x $(command -v fan-ctrl)
			if [ -f `command -v fan-ctrl` ]; then
				sudo rm -f $DIR/fan-ctrl.orig;
			else
				sudo mv -f $DIR/fan-ctrl.orig $DIR/fan-ctrl;
			fi
			fan-ctrl -h;
		else
			echo -e "This script requires an internet connection to update.";
			exit 0;
		fi
		;;
	m)
		while [ 1 ]
		do
		CHOICE=$(
		export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
		whiptail --backtitle "Menu Interface: Odroid Trip Point" --title "== Fan Control ==" --menu "" --nocancel 0 0 0 \
			"6)" "65°C" \
			"5)" "55°C" \
			"4)" "45°C" \
			"3)" "35°C" \
			"E)" "Exit .." 3>&2 2>&1 1>&3
		)
		case $CHOICE in
			"6)")
				clear -x
				fan-ctrl -6
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Trip point set to 65°C" 0 0
				;;
			"5)")
				clear -x
				fan-ctrl -5
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Trip point set to 55°C" 0 0
				;;
			"4)")
				clear -x
				fan-ctrl -4
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Trip point set to 45°C" 0 0
				;;
			"3)")
				clear -x
				fan-ctrl -3
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Trip point set to 35°C" 0 0
				;;
			"E)")
				clear -x
				exit 0
				;;
			esac
		done
		;;
	h)
		echo -e "${TXT}Odroid Trip Point${FIN}"
		echo -e "Usage: "
		echo ""
		echo -e "\t-6\t65°C"
		echo -e "\t-5\t55°C"
		echo -e "\t-4\t45°C"
		echo -e "\t-3\t35°C"
		echo ""
		echo -e "\t-r\tRun"
		echo -e "\t-u\tUpdate"
		echo ""
		exit 0
		;;

	esac
done

exit 0