#!/usr/bin/env bash
POINT="55000"
FIND=`command -v fan-ctrl`
DIR="/usr/local/bin/"
WHT="\e[1;37m"
FIN="\e[0m"

if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "6543ruh" OPTION; do
	case $OPTION in

	6)
		sudo sed -i "2s/.*/POINT="'"65000"'"/" /usr/local/bin/fan-ctrl
		fan-ctrl -r
		;;
	5)
		sudo sed -i "2s/.*/POINT="'"55000"'"/" /usr/local/bin/fan-ctrl
		fan-ctrl -r
		;;
	4)
		sudo sed -i "2s/.*/POINT="'"45000"'"/" /usr/local/bin/fan-ctrl
		fan-ctrl -r
		;;
	3)
		sudo sed -i "2s/.*/POINT="'"35000"'"/" /usr/local/bin/fan-ctrl
		fan-ctrl -r
		;;
	r)
		if [ -f /sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp ]; then
			echo $POINT | sudo tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp;
		else
			echo -e "You are missing trip_point_4_temp?";
			exit 0;
		fi
		;;
	u)
		if [[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
			sudo mv -f $FIND $FIND.orig
			sudo wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/fan-ctrl -P $DIR
			sudo chmod +x $FIND
			if [ -f $FIND ]; then
				sudo rm -f $FIND.orig;
			else
				sudo mv -f $FIND.orig $FIND;
			fi
			fan-ctrl -h;
		else
			echo -e "This script requires an internet connection to update.";
			exit 0;
		fi
		;;
	h)
		echo -e "${WHT}Odroid N2 Trip Point${FIN}"
		echo -e "Usage: "
		echo ""
		echo -e "\t-6\t65°C"
		echo -e "\t-5\t55°C"
		echo -e "\t-4\t45°C"
		echo -e "\t-3\t35°C"
		echo ""
		echo -e "\t-r\tRun"
		echo -e "\t-u\tUpdate"
		echo ""
		exit 0
		;;

	esac
done
