#!/bin/bash
# Description: Fan Control
# Destination: /usr/local/bin/fanctrl

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	echo -e "Your board is not supported."
	exit 0
fi
if [[ "$USER" == "root" ]]; then
	:;
else
	if [[ `command -v sudo` ]]; then
		if [[ $EUID -ne 0 ]]; then
			sudo "$0" "$@" 
			exit
		fi
	else
		echo "Please run this as root or with sudo privileges."
		exit 0
	fi
fi
if [[ -f "/etc/default/fanctrl" ]]; then
	. /etc/default/fanctrl
else
	echo 'POINT="55000"' | tee /etc/default/fanctrl
	sleep .25
	. /etc/default/fanctrl
fi

warning (){
WARNING_MSG="Argument is not supported."
echo -e "$WARNING_MSG"
exit 0
}

check (){
if [[ "$BOARD" == "bananapicm4" ]]; then
	X=`echo $POINT | sed 's/...$//'`
	Y="5"
	echo -e "Current trip points: ${POINT}, $(($X+$Y))000"
else
	echo -e "Current trip point: $POINT"
fi
}

run (){ # run script
if [[ "$BOARD" == "bananapicm4" ]]; then
	if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp" ]]; then
		echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp
		if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp" ]]; then
			X=`echo $POINT | sed 's/...$//'`
			Y="5"
			echo "$(($X+$Y))000" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp
		fi
	else
		echo -e "Trip point missing."
		exit 0
	fi
fi
if [[ "$BOARD" == "odroidn2l" || "$BOARD" == "odroidn2plus" ]]; then
	if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp" ]]; then
		echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp
	else
		echo -e "Trip point missing."
		exit 0
	fi
fi
if [[ "$BOARD" == "odroidxu4" ]]; then
	TZONE0="/sys/devices/virtual/thermal/thermal_zone0/trip_point_0_temp"
	TZONE1="/sys/devices/virtual/thermal/thermal_zone1/trip_point_0_temp"
	TZONE2="/sys/devices/virtual/thermal/thermal_zone2/trip_point_0_temp"
	TZONE3="/sys/devices/virtual/thermal/thermal_zone3/trip_point_0_temp"
	TZONE4="/sys/devices/virtual/thermal/thermal_zone4/trip_point_0_temp"
	if [[ -f "$TZONE0" ]] && [[ -f "$TZONE1" ]] && [[ -f "$TZONE2" ]] && [[ -f "$TZONE3" ]] && [[ -f "$TZONE4" ]]; then
		echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone{0,1,2,3,4}/trip_point_0_temp
		sleep .50
		# tap trip points twice
		echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone{0,1,2,3,4}/trip_point_0_temp > /dev/null 2>&1
	else
		echo -e "Trip point missing."
		exit 0
	fi
fi
}

temperature (){
echo 'POINT="'"${X}000"'"' | tee /etc/default/fanctrl > /dev/null 2>&1
source /etc/default/fanctrl
sleep .25
fanctrl run
}

update (){
if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
	echo -en "Updating fanctrl script"
	if [[ `command -v fanctrl` ]]; then
		mv -f /usr/local/bin/fanctrl /usr/local/bin/fanctrl.orig
	fi
	wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/fanctrl -P /usr/local/bin
	chmod +x $(command -v fanctrl)
	if [[ `command -v fanctrl` ]]; then
		echo -e " [done]"
		rm -f /usr/local/bin/fanctrl.orig
	else
		echo -e " [fail]"
		mv -f /usr/local/bin/fanctrl.orig /usr/local/bin/fanctrl
	fi
	fanctrl
else
	echo -e "This script requires an internet connection to update."
	exit 0
fi
}

if [ $# -eq 0 ]; then
	>&2 echo -e "Arguments: 65 60 55 50 45 40 35 30 25 check run update"
	exit 1
fi
case $1 in
	65|60|55|50|45|40|35|30|25|check|run|update)
	;;
	*)
	echo -e "Arguments: 65 60 55 50 45 40 35 30 25 check run update" >&2
	exit 1
esac

FANCTRL=`echo $1`
$FANCTRL 2>/dev/null

if [[ "$1" =~ ^[0-9]+$ ]]; then
	X="$1"
	temperature
fi

exit 0
