#!/bin/bash
# Description: Fan Control
# Destination: /usr/local/bin/fanctrl

if [[ -f "/etc/opt/board.txt" ]]; then
	. /etc/opt/board.txt
else
	echo -e "Your board is not supported."
	exit 0
fi
if [[ "$USER" == "root" ]]; then
	:;
else
	if [[ `command -v sudo` ]]; then
		if [[ $EUID -ne 0 ]]; then
			sudo "$0" "$@" 
			exit
		fi
	else
		echo "Please run this as root or with sudo privileges."
		exit 0
	fi
fi

# trip point
POINT="55000"
FINDME=`command -v fanctrl`

warning (){
WARNING_MSG="Argument is not supported."
echo -e "$WARNING_MSG"
exit 0
}

trip_point0 (){
TZONE0="/sys/devices/virtual/thermal/thermal_zone0/trip_point_0_temp"
TZONE1="/sys/devices/virtual/thermal/thermal_zone1/trip_point_0_temp"
TZONE2="/sys/devices/virtual/thermal/thermal_zone2/trip_point_0_temp"
TZONE3="/sys/devices/virtual/thermal/thermal_zone3/trip_point_0_temp"
if [[ -f "$TZONE0" ]] && [[ -f "$TZONE1" ]] && [[ -f "$TZONE2" ]] && [[ -f "$TZONE3" ]]; then
	echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone{0,1,2,3}/trip_point_0_temp
else
	echo -e "You are missing a trip point?"
	exit 0
fi
}

trip_point3 (){
if [[ -f "/sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp" ]]; then
	echo "$POINT" | tee /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp
else
	echo -e "You are missing trip_point_3_temp?"
	exit 0
fi
}

65(){ # 65°C
sed -i "s/^POINT=.*/POINT="'"65000"'"/" $FINDME
sleep .25
fanctrl run
}

55(){ # 55°C
sed -i "s/^POINT=.*/POINT="'"55000"'"/" $FINDME
sleep .25
fanctrl run
}

45(){ # 45°C
sed -i "s/^POINT=.*/POINT="'"45000"'"/" $FINDME
sleep .25
fanctrl run
}

35(){ # 35°C
sed -i "s/^POINT=.*/POINT="'"35000"'"/" $FINDME
sleep .25
fanctrl run
}

25(){ # 25°C
sed -i "s/^POINT=.*/POINT="'"25000"'"/" $FINDME
sleep .25
fanctrl run
}

run (){ # run script
if [[ "$BOARD" == "bananapicm4" || "$BOARD" == "odroidn2l" || "$BOARD" == "odroidn2plus" ]]; then
	trip_point3
fi
if [[ "$BOARD" == "odroidxu4" ]]; then
	trip_point0
fi
}

menu (){
while [ 1 ]
do
CHOICE=$(
export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
whiptail --backtitle "Current Trip Point: $POINT" --title "Fan Control" --menu "" --nocancel 0 0 0 \
	"6)" "65°C" \
	"5)" "55°C" \
	"4)" "45°C" \
	"3)" "35°C" \
	"2)" "25°C" \
	"E)" "Exit .." 3>&2 2>&1 1>&3
)
case $CHOICE in
	"6)")
		clear -x
		fanctrl 65
		export NEWT_COLORS='root=,black'
		whiptail --msgbox "    Trip point set to 65°C" 0 0
		;;
	"5)")
		clear -x
		fanctrl 55
		export NEWT_COLORS='root=,black'
		whiptail --msgbox "    Trip point set to 55°C" 0 0
		;;
	"4)")
		clear -x
		fanctrl 45
		export NEWT_COLORS='root=,black'
		whiptail --msgbox "    Trip point set to 45°C" 0 0
		;;
	"3)")
		clear -x
		fanctrl 35
		export NEWT_COLORS='root=,black'
		whiptail --msgbox "    Trip point set to 35°C" 0 0
		;;
	"2)")
		clear -x
		fanctrl 25
		export NEWT_COLORS='root=,black'
		whiptail --msgbox "    Trip point set to 25°C" 0 0
		;;
	"E)")
		clear -x
		exit 0
		;;
	esac
done
}

update (){
if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
	echo -en "Updating fanctrl script"
	if [[ `command -v fanctrl` ]]; then
		mv -f /usr/local/bin/fanctrl /usr/local/bin/fanctrl.orig
	fi
	wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/fanctrl -P /usr/local/bin
	chmod +x $(command -v fanctrl)
	if [[ `command -v fanctrl` ]]; then
		echo -e " [done]"
		rm -f /usr/local/bin/fan-ctrl.orig;
	else
		echo -e " [fail]"
		mv -f /usr/local/bin/fanctrl.orig /usr/local/bin/fanctrl
	fi
	fanctrl
else
	echo -e "This script requires an internet connection to update."
	exit 0
fi
}

if [ $# -eq 0 ]; then
	>&2 echo -e "Arguments: 65 55 45 35 25 menu run update"
	exit 1
fi
case $1 in
	65|55|45|35|25|menu|run|update)
	;;
	*)
	echo -e "Arguments: 65 55 45 35 25 menu run update" >&2
	exit 1
esac
FANCTRL=`echo $1`
$FANCTRL

exit 0
