#!/bin/bash

###
list () {
echo
content=$(curl --silent -L https://github.com/pyavitz/rpi-img-builder/releases/download/linux/version)
echo $content
echo
}

update () {
sudo rm -f /usr/local/bin/fetch
sudo wget -cq --show-progress https://github.com/pyavitz/scripts/raw/master/fetch -P /usr/local/bin
sudo chmod +x /usr/local/bin/fetch
}

###
rpi-4.19.y () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi-4.19.y\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi-4.19.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi-4.19.y.tar.xz
rm -f rpi-4.19.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi-4.19.y
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

rpi3-4.19.y () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi3-4.19.y\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi3-4.19.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi3-4.19.y.tar.xz
rm -f rpi3-4.19.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi3-4.19.y
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

rpi4-4.19.y () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi4-4.19.y\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi4-4.19.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi4-4.19.y.tar.xz
rm -f rpi4-4.19.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi4-4.19.y
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

### 
rpi-5.4.y () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi-5.4.y\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi-5.4.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi-5.4.y.tar.xz
rm -f rpi-5.4.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi-5.4.y
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

rpi3-5.4.y () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi3-5.4.y\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi3-5.4.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi3-5.4.y.tar.xz
rm -f rpi3-5.4.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi3-5.4.y
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

rpi4-5.4.y () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi4-5.4.y\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi4-5.4.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi4-5.4.y.tar.xz
rm -f rpi4-5.4.y.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi4-5.4.y
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

###
rpi-stable () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi-stable\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi-stable.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi-stable.tar.xz
rm -f rpi-stable.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi-stable
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

rpi3-stable () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi3-stable\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi3-stable.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi3-stable.tar.xz
rm -f rpi3-stable.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi3-stable
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

rpi4-stable () {
mkdir -p ~/.build
cd ~/.build
echo -e "\e[1;31mFetching rpi4-stable\e[0m"
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi4-stable.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mExtracting archive\e[0m"
tar xf rpi4-stable.tar.xz
rm -f rpi4-stable.tar.xz
echo -e "\e[1;31mDone.\e[0m"
echo
echo -e "\e[1;31mStarting install\e[0m"
cd rpi4-stable
sudo dpkg -i *.deb
cd ~
echo -e "\e[1;31mDone.\e[0m"
sudo rm -fdr ~/.build/*
}

if [ $# -eq 0 ]
then
        echo -e "\e[0;31mMissing options!\e[0m"
        echo "(run $0 -h for help)"
        echo ""
        exit 0
fi

ECHO="false"

while getopts "123hru" OPTION; do
        case $OPTION in

                1)
                        ECHO="4.19"
                        ;;
                2)
                        ECHO="5.4"
                        ;;
                3)
                        ECHO="stable"
                        ;;
                r)
                        ECHO="rev"
                        ;;
                u)
                        ECHO="up"
                        ;;
                h)
                        echo ""
                        echo "Fetch, Linux kernel installer for the Raspberry Pi Image Builder"
                        echo "https://github.com/pyavitz/rpi-img-builder"
                        echo "Usage: fetch -opt"
                        echo ""
                        echo -e "   \e[0m-1        Linux 4.19.y LTS\e[0m"
                        echo -e "   \e[0m-2        Linux 5.4.y LTS\e[0m"
                        echo -e "   \e[0m-3        Linux Stable Branch\e[0m"
                        echo -e "   \e[0m-r        Kernel Revisions\e[0m"
                        echo -e "   \e[0m-u        Update Fetch\e[0m"
                        echo -e "   \e[0m-h        Help\e[0m"
                        echo ""
                        echo "Should you come across any bugs, either open an issue on GitHub or talk"
                        echo "with us directly by joining our channel on Freenode; #debianarm-port"
                        exit 0
                        ;;

        esac
done

if [ $ECHO = "4.19" ]
then
        echo
        if ls /boot/bcm2708*.dtb > /dev/null 2>&1; then rpi-4.19.y ;
                else : > /dev/null 2>&1
        fi

        if ls /boot/bcm2710*.dtb > /dev/null 2>&1; then rpi3-4.19.y ;
                else : > /dev/null 2>&1
        fi

        if ls /boot/broadcom/bcm2711*.dtb > /dev/null 2>&1; then rpi4-4.19.y ;
                else : > /dev/null 2>&1
        fi
fi

if [ $ECHO = "5.4" ]
then
        echo
        if ls /boot/bcm2708*.dtb > /dev/null 2>&1; then rpi-5.4.y ;
                else : > /dev/null 2>&1
        fi

        if ls /boot/bcm2710*.dtb > /dev/null 2>&1; then rpi3-5.4.y ;
                else : > /dev/null 2>&1
        fi

        if ls /boot/broadcom/bcm2711*.dtb > /dev/null 2>&1; then rpi4-5.4.y ;
                else : > /dev/null 2>&1
        fi
fi

if [ $ECHO = "stable" ]
then
        echo
        if ls /boot/bcm2708*.dtb > /dev/null 2>&1; then rpi-stable ;
                else : > /dev/null 2>&1
        fi

        if ls /boot/bcm2710*.dtb > /dev/null 2>&1; then rpi3-stable ;
                else : > /dev/null 2>&1
        fi

        if ls /boot/broadcom/bcm2711*.dtb > /dev/null 2>&1; then rpi4-stable ;
                else : > /dev/null 2>&1
        fi
fi

if [ $ECHO = "rev" ]
then
        list;
fi

if [ $ECHO = "up" ]
then
        update;
fi
