#! /bin/sh
### BEGIN INIT INFO
# Provides: gadget
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop:
# Short-Description: Gadget mode
# Description:
### END INIT INFO

# chmod +x /etc/init.d/gadget
# update-rc.d gadget defaults 2

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Turn on gadget"
    /usr/local/sbin/gadget-mode 2>/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
