#!/usr/bin/env bash
GOVERNOR="performance"

if [ $# -eq 0 ]; then
	echo "Missing options!";
	echo "(run $0 -h for help)";
	echo "";
	exit 0;
fi

while getopts "copsruh" OPTION; do
	case $OPTION in

	c)
		sudo sed -i "2s/.*/GOVERNOR="'"conservative"'"/" /usr/local/bin/governor
		governor -r
		;;
	o)
		sudo sed -i "2s/.*/GOVERNOR="'"ondemand"'"/" /usr/local/bin/governor
		governor -r
		;;
	p)
		sudo sed -i "2s/.*/GOVERNOR="'"performance"'"/" /usr/local/bin/governor
		governor -r
		;;
	s)
		sudo sed -i "2s/.*/GOVERNOR="'"schedutil"'"/" /usr/local/bin/governor
		governor -r
		;;
	r)
		echo "$GOVERNOR" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
		;;
	u)
		sudo mv -f /usr/local/bin/governor /usr/local/bin/governor.orig
		sudo wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/governor -P /usr/local/bin/
		sudo chmod +x /usr/local/bin/governor
		if [ -f /usr/local/bin/governor ]; then
			sudo rm -f /usr/local/bin/governor.orig;
		else
			sudo mv -f /usr/local/bin/governor.orig /usr/local/bin/governor;
		fi
		governor -h
		;;
	h)
		echo -e "\e[1;37mCPU frequency scaling\e[0m"
		echo "Usage: "
		echo ""
		echo "   -c       Conservative"
		echo "   -o       Ondemand"
		echo "   -p       Performance"
		echo "   -s       Schedutil"
		echo ""
		echo "   -r       Run"
		echo "   -u       Update"
		echo ""
		exit 0
		;;
	esac
done
