#!/usr/bin/env bash
GOVERNOR="performance"

performance () {
sudo sed -i "2s/.*/GOVERNOR="'"performance"'"/" /usr/local/bin/governor
governor -r
}

ondemand () {
sudo sed -i "2s/.*/GOVERNOR="'"ondemand"'"/" /usr/local/bin/governor
governor -r
}

conservative () {
sudo sed -i "2s/.*/GOVERNOR="'"conservative"'"/" /usr/local/bin/governor
governor -r
}

run () {
echo $GOVERNOR | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
}

# Commands
if [ $# -eq 0 ]
then
        echo "Missing options!"
        echo "(run $0 -h for help)"
        echo ""
        exit 0
fi

ECHO="false"

while getopts "coph" OPTION; do
        case $OPTION in

                c)
                        ECHO="conservative"
                        ;;
                o)
                        ECHO="ondemand"
                        ;;
                p)
                        ECHO="performance"
                        ;;
                r)
                        ECHO="run"
                        ;;
                h)
                        echo "Set the governor"
                        echo "Usage: swh -opt"
                        echo ""
                        echo "   -c       Conservative"
                        echo "   -o       Ondemand"
                        echo "   -p       Performance"
                        echo ""
                        exit 0
                        ;;

        esac
done

if [ $ECHO = "conservative" ]
then
        conservative;
fi
if [ $ECHO = "ondemand" ]
then
        ondemand;
fi
if [ $ECHO = "performance" ]
then
        performance;
fi
if [ $ECHO = "run" ]
then
        run;
fi
