#!/usr/bin/env bash
# Description: Set governor scheduler
# Destination: /usr/local/bin/governor

export LANG=$LANG:C
if [[ $EUID -ne 0 ]]; then
	sudo "$0" "$@" 
	exit 0
fi

if [[ -f "/etc/default/governor" ]]; then
	. /etc/default/governor
else
	echo 'GOVERNOR="performance"' | tee /etc/default/governor
	sleep .25
	. /etc/default/governor
fi

if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "copsrumh" OPTION; do
	case $OPTION in

	c)
		echo 'GOVERNOR="conservative"' | tee /etc/default/governor > /dev/null 2>&1
		. /etc/default/governor
		governor -r
		;;
	o)
		echo 'GOVERNOR="ondemand"' | tee /etc/default/governor > /dev/null 2>&1
		. /etc/default/governor
		governor -r
		;;
	p)
		echo 'GOVERNOR="performance"' | tee /etc/default/governor > /dev/null 2>&1
		. /etc/default/governor
		governor -r
		;;
	s)
		echo 'GOVERNOR="schedutil"' | tee /etc/default/governor > /dev/null 2>&1
		. /etc/default/governor
		governor -r
		;;
	r)
		echo "$GOVERNOR" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
		;;
	u)
		mv -f /usr/local/bin/governor /usr/local/bin/governor.orig
		wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/governor -P /usr/local/bin/
		chmod +x $(command -v governor)
		if [[ -f "/usr/local/bin/governor" ]]; then
			rm -f /usr/local/bin/governor.orig
		else
			mv -f /usr/local/bin/governor.orig /usr/local/bin/governor
		fi
		governor -h
		;;
	m)
		while [ 1 ]
		do
		CHOICE=$(
		export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
		whiptail --backtitle "Menu Interface: Governor" --title "Governor" --menu "" --nocancel 0 0 0 \
			"1)" "Conservative" \
			"2)" "Ondemand" \
			"3)" "Performance" \
			"4)" "Schedutil" \
			"E)" "Exit .." 3>&2 2>&1 1>&3
		)
		case $CHOICE in
			"1)")
				governor -c
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Governor set to Conservative" 0 0
				;;
			"2)")
				governor -o
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Governor set to Ondemand" 0 0
				;;
			"3)")
		        	governor -p
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Governor set to Performance" 0 0
				;;
			"4)")
				governor -s
				export NEWT_COLORS='root=,black'
				whiptail --msgbox "    Governor set to Schedutil" 0 0
				;;
			"E)")
				clear -x
				exit 0
				;;
			esac
		done
		;;
	h)
		echo -e "\e[1;37mCPU frequency scaling\e[0m"
		echo -e "Usage: "
		echo ""
		echo -e "\t-c\tConservative"
		echo -e "\t-o\tOndemand"
		echo -e "\t-p\tPerformance"
		echo -e "\t-s\tSchedutil"
		echo ""
		echo -e "\t-r\tRun"
		echo -e "\t-u\tUpdate"
		echo ""
		exit 0
		;;
	esac
done

exit 0
