#!/bin/bash
# Debian Bullseye (ARM)
# sudo wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/install-de -P /usr/local/bin; sudo chmod +x /usr/local/bin/install-de
# Execute: install-de

DOWNLOAD="aria2c -c --download-result=hide --console-log-level=error --disable-ipv6=true --summary-interval=0 --show-files=false"

XFCE="xfce4 xinit thunar mousepad gvfs-backends gvfs-fuse gnome-screensaver feh \
	xfce4-terminal avahi-utils pulseaudio blueman xfce4-goodies file-roller \
	fbi alacarte chromium lightdm-gtk-greeter lightdm x11-xserver-utils xserver-xorg"

MESADEV="llvm-dev ninja-build meson libvdpau-dev libxvmc-dev libva-dev libomxil-bellagio-dev python3-mako \
	libdrm-nouveau2 libdrm-dev wayland-protocols libwayland-egl-backend-dev libunwind-dev libxdamage-dev \
	libxcb-glx0-dev libxcb-shm0-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev \
	libxshmfence-dev libxxf86vm-dev libxrandr-dev valgrind mpv"

### CHECK ARIA2
aria2c_check(){
if [ `command -v aria2c` ]; then
	:;
else
	sudo apt install -y aria2;
fi
}

### MESA 20.3
mesa_install(){
echo
echo Installing Mesa 20.3
sudo apt install -y ${MESADEV}

cd ~
mkdir mesa
cd mesa
${DOWNLOAD} https://gitlab.freedesktop.org/mesa/mesa/-/archive/20.3/mesa-20.3.tar.gz
tar xf mesa-20.3.tar.gz
rm -f mesa-20.3.tar.gz
mkdir -p mesa-20.3/build
cd mesa-20.3/build
sudo meson --prefix=/usr -Dglx=disabled -Dplatforms=auto -Dllvm=disabled -Dvulkan-drivers='' -Ddri-drivers='' -Dgallium-drivers=vc4,v3d,kmsro ..
sudo ninja install
cd ~
sudo rm -fdr mesa
sudo apt purge -y --autoremove ninja-build meson
sudo chown -R $USER:$USER /home/$USER
echo Done.
}

### RUN
sudo apt update
sudo apt upgrade -y
aria2c_check
#mesa_install
echo ""
sudo apt install -y ${XFCE}
sudo apt purge -y light-locker
sudo wget -cq https://raw.githubusercontent.com/pyavitz/rpi-img-builder/xfce/files/scripts/sleep-locker -P /usr/local/bin
sudo chmod +x /usr/local/bin/sleep-locker
sudo chown root:root /usr/local/bin/sleep-locker
sudo chown -R $USER:$USER /home/$USER
sudo adduser $USER lightdm
sudo usermod -a -G render $USER
sudo sed -i "s/#autologin-user=/autologin-user=$USER/g" /etc/lightdm/lightdm.conf
if [ -f /boot/config.txt ]; then
	sudo sed -i "s/#dtoverlay=vc4-kms-v3d/dtoverlay=vc4-kms-v3d/g" /boot/config.txt;
	sudo sed -i "s/dtoverlay=vc4-fkms-v3d/#dtoverlay=vc4-fkms-v3d/g" /boot/config.txt;
fi
mkdir -p ~/.local/share/applications
echo "NoDisplay=true" | tee ~/.local/share/applications/xfburn.desktop > /dev/null 2>&1
echo ""
echo -e "You may now reboot ..."
sudo rm -f /usr/local/bin/install-de
