#!/bin/bash
# Run script from openbox autostart
# If thermals drop below 55*C restart kiosk

# verbosity
#set -x

# dynamic variables
number (){
LOW="0"
HIGH="54"
NUMBER=$(cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2)
}

# url and html file
URL="http://feed.com/"
HTML="cams.html"

# allow 1 minute before running loop
sleep 60

# run loop
while true; do
	service avahi-daemon restart # make sure avahi is available
	number
	if ((NUMBER >= $LOW && NUMBER <= $HIGH)); then
		killall chromium > /dev/null 2>&1; killall chromium > /dev/null 2>&1
		rm -fdr ${HOME}/.cache/chromium
		rm -fdr ${HOME}/.config/chromium
		DISPLAY=:0 chromium --noerrdialogs --incognito --kiosk --force-device-scale-factor=1 --disk-cache-dir=/tmp/null --enable-features=WebUIDarkMode --force-dark-mode ${URL}${HTML} > /dev/null 2>&1 &
		sleep 300
	else
		sleep 300
	fi
done

exit 0
