#!/bin/bash
URL="http://ipaddress/"
FILE="file.html"

if [[ `grep -w "ID=debian" "/etc/os-release"` ]]; then
	:;
else
	echo ""
	echo "This script was created to be used on Debian"
	exit > /dev/null 2>&1;
fi

if [ command -v chromium ]; then
	echo "Restarting Chromium ..."
	if [ command -v killall ]; then
		killall chromium > /dev/null 2>&1;
	else
		pkill -o chromium > /dev/null 2>&1;
	fi
	sleep 1s
	if [ -e ~/.cache/chromium ]; then
		rm -fdr ~/.cache/chromium;
	fi
	if [ -e ~/.config/chromium ]; then
		rm -fdr ~/.config/chromium;
	fi
	DISPLAY=:0 chromium --noerrdialogs --incognito --kiosk --force-device-scale-factor=1 --disk-cache-dir=/tmp/null ${URL}${FILE} > /dev/null 2>&1 &
	echo "Done.";
else
	echo ""
	echo "You do not have Chromium installed."
	exit > /dev/null 2>&1;
fi
