#!/bin/bash
# DEBIAN IMAGE BUILDER: SYSTEM MENU INTERFACE

supported_list(){
source /etc/opt/board.txt
if [[ "$BOARD" == "odroidn2" ]]; then
	BOARD_PN="Odroid N2";
	supported=1;
fi
if [[ "$BOARD" == "odroidn2plus" ]]; then
	BOARD_PN="Odroid N2+";
	supported=1;
fi
if [[ "$BOARD" == "radxazero" ]]; then
	BOARD_PN="Radxa Zero";
	supported=1;
fi
if [[ "$BOARD" == "nanopc" ]]; then
	BOARD_PN="NanoPC-T4";
	supported=1;
fi
if [[ "$BOARD" == "rockpro64" ]]; then
	BOARD_PN="RockPRO64";
	supported=1;
fi
}

overclock(){
if [ -e /etc/opt ]; then
	echo "overclock=1" | sudo tee /etc/opt/overclock.txt;
	sudo service tweaks restart;
else
	mkdir -p /etc/opt;
	echo "overclock=1" | sudo tee /etc/opt/overclock.txt;
	sudo service tweaks restart;
fi
}

while [ 1 ]
do
CHOICE=$(
export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
whiptail --backtitle "Menu Interface: System Settings" --title "System Settings" --menu "" --nocancel 0 25 0 \
	"1)" "Governor" \
	"2)" "Wireless" \
	"3)" "Locales" \
	"4)" "Keyboard" \
	"5)" "Timezone" \
	"6)" "Overclock" \
	"Q)" "Quit ..." 3>&2 2>&1 1>&3
)

case $CHOICE in
	"1)")
		governor -m
		;;
	"2)")
		swh -m
		;;
	"3)")
		sudo dpkg-reconfigure locales
		;;
	"4)")
		sudo dpkg-reconfigure keyboard-configuration
		;;
	"5)")
		sudo dpkg-reconfigure tzdata
		;;
	"6)")
		export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
		supported_list
		if [ $supported -eq 1 ]; then
			if (whiptail --backtitle "Board: $BOARD_PN" --title "$BOARD_PN" --yesno "   Overclock?" 0 0); then
				overclock;
			fi
		else
			whiptail --msgbox "Your board is not supported." 0 0;
		fi
		;;
	"Q)")
		exit 0
		;;
	esac
done
exit 0
