#!/bin/bash
##### https://github.com/ccrisan/motioneye/wiki/Install-On-Debian
# Debian Buster
echo Starting install as $USER
echo
echo Installing needed packages and dependencies.
sleep 1s
sudo apt update
sudo apt upgrade -y 
sudo apt install -y \
	apache2 motion ffmpeg v4l-utils python-pip python-pil python-dev python-setuptools \
	python-pycurl python-tornado curl libssl-dev libcurl4-openssl-dev libjpeg-dev libz-dev
echo Done.
sleep 1s
echo
echo Installing motionEye.
sudo pip install motioneye
echo Done.
sleep 1s
echo
echo Setting up configuration and media directory.
sudo mkdir -p /etc/motioneye
sudo cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
sudo mkdir -p /var/lib/motioneye
sudo cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
echo Done.
sleep 1s
echo
echo Enabling services
sudo systemctl daemon-reload
sudo systemctl enable apache2
sudo systemctl enable motioneye
sudo systemctl start apache2
sudo systemctl start motioneye
echo Done.
echo
sleep 1s
echo Please look over the instructions and wiki for further information.