#!/bin/bash

SUPPORTED_ARCH=`uname -m`

if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "iuh" OPTION; do
	case $OPTION in

		i)
			if [[ "$SUPPORTED_ARCH" == "armv7l" ]]; then
				sudo apt update
				sudo apt --no-install-recommends install -y ca-certificates curl python3 python3-distutils
				curl -sSfO 'https://bootstrap.pypa.io/get-pip.py'
				sudo python3 get-pip.py
				rm get-pip.py
				printf '%b' '[global]\nextra-index-url=https://www.piwheels.org/simple/\n' | sudo tee /etc/pip.conf > /dev/null
				sudo python3 -m pip install 'https://github.com/motioneye-project/motioneye/archive/dev.tar.gz'
				sudo motioneye_init
			else
				echo "Your $SUPPORTED_ARCH is not supported by this script."
			fi
			;;
		u)
			if [[ "$SUPPORTED_ARCH" == "armv7l" ]] || [[ `systemctl status motioneye | grep -w "meyectl"` ]]; then
				sudo systemctl stop motioneye
				sudo python3 -m pip install --upgrade --force-reinstall --no-deps 'https://github.com/motioneye-project/motioneye/archive/dev.tar.gz'
				sudo systemctl start motioneye
			else
				echo "Your $SUPPORTED_ARCH is not supported by this script."
			fi
			;;
		h)
			echo ""
			echo -e "MotionEYE"
			echo ""
			echo -e "\t-m\tInstall"
			echo -e "\t-u\tUpgrade"
			echo ""
			echo -e "\t-h\tHelp"
			echo ""
			exit 0
			;;
	esac
done
