#!/bin/bash
# depends on cifs-utils
GHURL="https://raw.githubusercontent.com/pyavitz/scripts/master"
ADDR="10.0.0.1"
FOLDER="Name"
MNT="/your/location"
USER="user"
USERID="user"
PASSWD="password"

# Commands
if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "muUh" OPTION; do
	case $OPTION in

		m)
			sudo mount -t cifs //$ADDR/$FOLDER $MNT -o username=$USER,password=$PASSWD,rw,uid=$USERID
			;;
		u)
			sudo umount $MNT
			;;
		U)
			if [[ `wget -S --spider ${GHURL}/nmount 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
				sudo mv -f /usr/local/bin/nmount /usr/local/bin/nmount.orig;
				sudo wget -cq ${GHURL}/nmount -P /usr/local/bin;
				if [[ -f "/usr/local/bin/nmount" ]]; then
					sudo chmod +x /usr/local/bin/nmount;
					sudo rm -f /usr/local/bin/nmount.orig;
				else
					sudo mv -f /usr/local/bin/nmount.orig /usr/local/bin/nmount;
				fi
			fi
			nmount -h
			;;
		h)
			echo ""
			echo -e "Mount Network Share"
			echo ""
			echo -e "\t-m\tMount"
			echo -e "\t-u\tUnmount"
			echo ""
			echo -e "\t-h\tHelp"
			echo ""
			exit 0
			;;
	esac
done
