#!/bin/bash
# depends on cifs-utils

if [[ "$USER" == "root" ]]; then
	:;
else
	if [[ `command -v sudo` ]]; then
		export LANG=$LANG:C
		if [[ $EUID -ne 0 ]]; then
			sudo "$0" "$@" 
			exit
		fi
	else
		echo "Please run this as root or with sudo privileges."
		exit 0
	fi
fi

GHURL="https://raw.githubusercontent.com/pyavitz/scripts/master"
if [ -f ~/.config/nmount ]; then
	source ~/.config/nmount
else
	ADDR="10.0.0.1"
	FOLDER="Name"
	MNT="/your/location"
	USER="user"
	USERID="user"
	PASSWD="password"
fi

# Commands
if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "muUh" OPTION; do
	case $OPTION in

		m)
			mount -t cifs //$ADDR/$FOLDER $MNT -o username=$USER,password=$PASSWD,rw,uid=$USERID
			;;
		u)
			umount $MNT
			;;
		U)
			if [[ `wget -S --spider ${GHURL}/nmount 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
				mv -f /usr/local/bin/nmount /usr/local/bin/nmount.orig;
				wget -cq ${GHURL}/nmount -P /usr/local/bin;
				if [ -f /usr/local/bin/nmount ]; then
					chmod +x /usr/local/bin/nmount;
					rm -f /usr/local/bin/nmount.orig;
				else
					mv -f /usr/local/bin/nmount.orig /usr/local/bin/nmount;
				fi
			fi
			nmount -h
			;;
		h)
			echo ""
			echo -e "Mount Network Share"
			echo ""
			echo -e "\t-m\tMount"
			echo -e "\t-u\tUnmount"
			echo ""
			echo -e "\t-h\tHelp"
			echo ""
			exit 0
			;;
	esac
done
