#!/bin/bash
# Remove zstd support from dpkg for the Raspberry Pi 4B

echo -e "Ubuntu Impish / Jammy Hack ..."
sleep 1s
cd ~
sudo apt update; sudo apt upgrade -y
sudo apt install -y debhelper-compat po4a libbz2-dev libzstd-dev liblzma-dev libselinux1-dev zlib1g-dev
mkdir build
cd build
wget -cq http://archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg_1.20.9ubuntu2.tar.xz
tar -xf dpkg_1.20.9ubuntu2.tar.xz
cd dpkg-1.20.9ubuntu1
wget -cq https://github.com/pyavitz/binary/releases/download/060420/remove-zstd-support.patch
patch -p1 < remove-zstd-support.patch
rm -f remove-zstd-support.patch
dpkg-buildpackage -us -uc
cd ..
sudo dpkg -i dpkg_1.20.9ubuntu2_arm64.deb dpkg-dev_1.20.9ubuntu2_all.deb libdpkg-perl_1.20.9ubuntu2_all.deb
cd ~
rm -fdr build
if [ -e /etc/apt/preferences ]; then
	rm -f /etc/apt/preferences;
fi
sudo tee /etc/apt/preferences <<EOF
Package: rpi-eeprom linux-firmware linux-firmware-raspi2 pi-bluetooth raspberrypi-sys-mods dpkg dpkg-dev libdpkg-perl
Pin: release o=Ubuntu
Pin-Priority: 1
EOF
sudo apt update
echo -e "Done."
