#!/bin/bash
# sshot, takes screenshot of computer A and moves it to computer B
# depends: scrot, ssh

DATE="$(date +%F)"
TIME="$(date +%T | sed 's/://g' | sed 's/..$//')"
USER="user@ipaddress"
SHOT='DISPLAY=:0 scrot -d 1'

DESC="Fetching Screenshot"
IMAGE="image-file-name"
NAME="${IMAGE}-${DATE}-${TIME}"

echo ""
echo -e "${DESC} ..."
ssh ${USER} ${SHOT}
scp -3 ${USER}:~/*.png ~/${NAME}.png
ssh ${USER} 'rm ~/*.png'
echo -e "Done."
echo ""

exit 0
