#!/usr/bin/env bash
# Description: WiFi config helper
# Destination: /usr/local/bin/swh

export LANG=$LANG:C
if [[ $EUID -ne 0 ]]; then
	sudo "$0" "$@" 
	exit 0
fi

INTERFACE="wlan0"
TXT="\033[0m"
FIN="\e[0m"

spinner(){
local i sp n
sp='|\-/'
n=${#sp}
while sleep 0.1; do
	printf "%s\b" "${sp:i++%n:1}"
done
}

# Commands
if [ $# -eq 0 ]; then
	echo "Missing options!"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

while getopts "hsSudrWIUm" OPTION; do
	case $OPTION in

	s)
		echo -en "${TXT}"
		echo -en "Scanning: "; spinner &

		printf '\n'
		iwlist ${INTERFACE} scan | grep 'ESSID:\|Frequency:\|Quality=\|Encryption key:'

		kill "$!" # kill the spinner
		printf '\n'
		echo -en "${FIN}"
		read -p "Press enter to continue."
		;;
	S)
		echo ""
		echo -en "Scan specific SSID: "
		read SSID
		iwlist ${INTERFACE} scanning | grep -C5 -i -w "$SSID"
		echo ""
		read -p "Press enter to continue."
		;;
	u)
		echo ""
		echo "Bringing up interface."
		ifup ${INTERFACE}
		echo "Done."
		echo ""
		;;
	d)
		echo ""
		echo "Bringing down interface."
		ifdown ${INTERFACE}
		echo "Done."
		echo ""
		;;
	r)
		echo ""
		echo "Restarting ..."
		ifdown ${INTERFACE}
		sleep .75
		sudo ifup ${INTERFACE}
		;;
	W)
		nano /etc/wpa_supplicant/wpa_supplicant.conf
		;;
	I)
		nano /etc/network/interfaces
		;;
	U)
		if [[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
			mv -f /usr/local/bin/swh /usr/local/bin/swh.orig
			wget -cq https://raw.githubusercontent.com/pyavitz/scripts/master/swh -P /usr/local/bin/
			chmod +x $(command -v swh)
			if [[ `command -v swh` ]]; then
				rm -f /usr/local/bin/swh.orig
			else
				mv -f /usr/local/bin/swh.orig /usr/local/bin/swh
			fi
			swh -h
		else
			echo -e "This script requires an internet connection to update."
			exit 0
		fi
		;;
	m)
		while [ 1 ]
		do
		CHOICE=$(
		export NEWT_COLORS='root=,black roottext=lightgray,black title=black,lightgray'
		whiptail --backtitle "Menu Interface: Simple Wifi Helper" --title "Simple Wifi Helper" --menu "" --nocancel 0 0 0 \
			"1)" "Scan for SSID's" \
			"2)" "Bring up interface" \
			"3)" "Bring down interface" \
			"4)" "Restart interface" \
			"5)" "Edit wpa supplicant" \
			"6)" "Edit interface" \
			"E)" "Exit .." 3>&2 2>&1 1>&3
		)
		case $CHOICE in
			"1)")
				swh -s
				;;
			"2)")
				swh -u
				;;
			"3)")
				swh -d
				;;
			"4)")
				swh -r
				;;
			"5)")
				swh -W
				;;
			"6)")
				swh -I
				;;
			"E)")
				clear -x
				exit 0
				;;
			esac
		done
		;;
	h)
		echo -e "${TXT}Simple wifi helper${FIN}"
		echo -e "Usage: "
		echo ""
		echo -e "\t-s\tScan for SSID's"
		echo -e "\t-u\tBring up interface"
		echo -e "\t-d\tBring down interface"
		echo -e "\t-r\tRestart interface"
		echo -e "\t-W\tEdit wpa supplicant"
		echo -e "\t-I\tEdit interfaces"
		echo ""
		exit 0
		;;
	esac
done
