#!/bin/bash
### Depends: imagemagick and ffmpeg
WHT="\e[1;37m"
FIN="\e[0m"
FRAMES="10"

gray_scale(){
echo -e "${WHT}Converting jpg to gray scale.${FIN}"
mogrify -colorspace gray *.jpg
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Creating time lapse video.${FIN}"
ffmpeg -r $FRAMES -f image2 -pattern_type glob -i '*.jpg' -s 1280x720 -vcodec libx264 timelapse_gray.mp4
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Results:${FIN}"
ls *.mp4
}

color_scale(){
echo -e "${WHT}Creating time lapse video.${FIN}"
ffmpeg -r $FRAMES -f image2 -pattern_type glob -i '*.jpg' -s 1280x720 -vcodec libx264 timelapse_color.mp4
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Results:${FIN}"
ls *.mp4
}

gray_scale_convert(){
echo -e "${WHT}Converting jpg to png.${FIN}"
mogrify -format png *.jpg
rm -f *.jpg
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Converting png to gray scale.${FIN}"
mogrify -colorspace gray *.png
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Creating time lapse video.${FIN}"
ffmpeg -r $FRAMES -f image2 -pattern_type glob -i '*.png' -s 1280x720 -vcodec libx264 timelapse_gray.mp4
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Results:${FIN}"
ls *.mp4
}

color_scale_convert(){
echo -e "${WHT}Converting jpg to png.${FIN}"
mogrify -format png *.jpg
rm -f *.jpg
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Creating time lapse video.${FIN}"
ffmpeg -r $FRAMES -f image2 -pattern_type glob -i '*.png' -s 1280x720 -vcodec libx264 timelapse_color.mp4
echo -e "${WHT}Done.${FIN}"
echo
echo -e "${WHT}Results:${FIN}"
ls *.mp4
}

# Commands
if [ $# -eq 0 ]; then
	echo -e "\e[0;31mMissing options!${FIN}"
	echo "(run $0 -h for help)"
	echo ""
	exit 0
fi

ECHO="false"

while getopts "cgCGh" OPTION; do
        case $OPTION in

                c)
                        ECHO="color"
                        ;;
                g)
                        ECHO="gray"
                        ;;
                C)
                        ECHO="color_convert"
                        ;;
                G)
                        ECHO="gray_convert"
                        ;;
                h)                       
                        echo -e "${WHT}Create a time lapse video${FIN}"
                        echo "Usage: Place script inside image directory"
                        echo ""
                        echo -e "   -c        Color Scale Video"
                        echo -e "   -g        Gray Scale Video"
                        echo -e "   -C        Color Scale Video (JPG to PNG)"
                        echo -e "   -G        Gray Scale Video (JPG to PNG)"
                        echo ""
                        exit 0
                        ;;

        esac
done

if [ $ECHO = "color" ]; then
	color_scale;
fi

if [ $ECHO = "gray" ]; then
	gray_scale;
fi

if [ $ECHO = "color_convert" ]; then
	color_scale_convert;
fi

if [ $ECHO = "gray_convert" ]; then
	gray_scale_convert;
fi
