#!/bin/bash
# Raspberry Pi Firmware
RED="\e[1;31m"
FIN="\e[0m"

firmware(){
FWURL="https://github.com/pyavitz/firmware.git"
FWDEST="/lib/firmware/raspberrypi"
RBFALSE="sudo git config pull.rebase false"
echo -e "${RED}Checking firmware${FIN}" ...
if ls /usr/bin/git > /dev/null 2>&1;
	then :;
	else sudo apt install git -y;
fi
if ls ${FWDEST}/.git > /dev/null 2>&1;
	then cd ${FWDEST} && ${RBFALSE} && sudo git pull;
	else sudo git clone ${FWURL} ${FWDEST}
fi
sudo ln -srf /lib/firmware/raspberrypi/* /lib/firmware/brcm/
echo -e "${RED}Done${FIN}".
cd ~
}

firmware
