#!/bin/bash

update () {
sudo mv -f /usr/local/bin/wifidrv /usr/local/bin/wifidrv.orig
sudo wget -cq --show-progress https://github.com/pyavitz/scripts/raw/master/wifidrv -P /usr/local/bin
sudo chmod +x /usr/local/bin/wifidrv
if ls /usr/local/bin/wifidrv > /dev/null 2>&1;
   then sudo rm -f /usr/local/bin/wifidrv.orig ;
   else sudo mv -f /usr/local/bin/wifidrv.orig /usr/local/bin/wifidrv
fi
wifidrv -h
}

rtl88x2bu () {
mkdir -p ~/.build
cd ~/.build
echo
echo Checking for dkms.
sudo apt update
sudo apt install dkms git -y
echo
echo Fetching . . . rtl88x2bu.
git clone https://github.com/mabrand/rtl88x2bu.git -b linux-5.8-compatibility rtl88x2bu
cd rtl88x2bu
VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
sudo dkms add -m rtl88x2bu -v ${VER}
sudo dkms build -m rtl88x2bu -v ${VER}
sudo dkms install -m rtl88x2bu -v ${VER}
sudo modprobe 88x2bu
sudo rm -fdr ~/.build/*
echo Done.
}

rtl8812au () {
mkdir -p ~/.build
cd ~/.build
echo
echo Checking for dkms.
sudo apt update
sudo apt install dkms git -y
echo
echo Fetching . . . rtl8812au.
git clone https://github.com/aircrack-ng/rtl8812au.git
cd rtl8812au
sudo make dkms_install
sudo rm -fdr ~/.build/*
echo Done.
}

rtl8821cu () {
mkdir -p ~/.build
cd ~/.build
echo
echo Fetching . . . rtl8821cu.
git clone https://github.com/brektrou/rtl8821CU.git
cd rtl8821CU
sed -i "s/^CONFIG_RTW_DEBUG.*/CONFIG_RTW_DEBUG = n/" Makefile
sed -i "s/^CONFIG_MP_VHT_HW_TX_MODE.*/CONFIG_MP_VHT_HW_TX_MODE = n/" Makefile
sudo ln -srf /usr/src/linux-headers-$(uname -r)/arch/arm64 /usr/src/linux-headers-$(uname -r)/arch/aarch64
make -j4
sudo insmod 8821cu.ko > /dev/null 2>&1
sudo make install
cd ~
sudo rm -fdr ~/.build/*
echo Done.
}

# Commands
if [ $# -eq 0 ]
then
        echo "Missing options!"
        echo "(run $0 -h for help)"
        echo ""
        exit 0
fi

ECHO="false"

while getopts "hu123" OPTION; do
        case $OPTION in

                1)
                        ECHO="rtl8812au"
                        ;;
                2)
                        ECHO="rtl88x2bu"
                        ;;
                3)
                        ECHO="rtl8821cu"
                        ;;
                u)
                        ECHO="up"
                        ;;

                h)
                        echo ""
                        echo "Usage: wifidrv -opt"
                        echo ""
                        echo "   -1     rtl8812au (aircrack)"
                        echo "   -2     rtl88x2bu (cilynx)"
                        echo "   -3     rtl8821cu (brektrou)"
                        echo "   -u     update script"
                        echo ""
                        exit 0
                        ;;

        esac
done

if [ $ECHO = "rtl88x2bu" ]
then
        rtl88x2bu;
fi
if [ $ECHO = "rtl8812au" ]
then
        rtl8812au;
fi
if [ $ECHO = "rtl8821cu" ]
then
        rtl8821cu;
fi
if [ $ECHO = "up" ]
then
        update;
fi
