#!/bin/bash
# Description: Write operational image to usb
# Destination: /usr/local/bin/write2usb

USB="/dev/sda"
ERROR="$(ls {/dev/sdb,/dev/sdc,/dev/sdd} 2> /dev/null)"
PI_EEPROM="pieeprom-2021-12-02"
WHT="\e[1;37m"
YLW="\e[1;33m"
FIN="\e[0m"

### RUN AS ROOT
run_as_root(){
if [ "$USER" != "root" ]; then
        echo "Please run this as root or with sudo privileges."
        exit 1
fi
}

internet_check(){
if [[ `command -v wget` ]]; then
	[[ `wget -S --spider http://github.com 2>&1 | grep 'HTTP/1.1 200 OK'` ]];
else
	if [[ `curl -I https://github.com 2>&1 | grep 'HTTP/2 200'` ]]; then
		echo -e "${WHT}Installing missing depends${FIN}."
		sudo apt update
		sudo apt upgrade -y
		sudo apt install -y wget;
	else
		echo -e "This script requires an internet connection."
		exit;
	fi
fi
if [[ `command -v aria2c` ]]; then
	echo -e "${WHT}Installing missing depends${FIN}."
	sudo apt update
	sudo apt upgrade -y
	sudo apt install -y aria2;
fi
}

correct(){
if [ -e "$USB" ]; then
    echo ""
    echo -e "${WHT}$USB found${FIN}."
else 
    check_node
fi
}

confirm(){
echo -e "${YLW}If more than one USB storage device is connected"
echo -e "then select no... or risk losing important data${FIN}."
echo -e ""
read -p "Continue (y/n)?" choice
case "$choice" in 
  y|Y ) echo && echo -e "${WHT}Confirmed${FIN}!";;
  n|N ) echo && echo -e "${YLW}You have chosen${FIN}... ${YLW}wisely${FIN}." && exit 0;;
  * ) echo && echo -e "${YLW}Invalid choice${FIN}." && exit 0;;
esac
}

check_progressbar(){
DPB="sudo wget -cq https://raw.githubusercontent.com/pyavitz/bash_progress_bar/master/progress_bar.sh -P /etc/opt/"
MPB="sudo mv -f /etc/opt/progress_bar.sh /etc/opt/progressbar.txt"
if [ -e /etc/opt/progressbar.txt ]; then
	:;
else
	$DPB;
	$MPB;
fi
}

### CHECK FOR NODE
check_node(){
echo ""
echo -e "You ${WHT}don't${FIN} have a ${WHT}USB storage device${FIN} connected."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please connect a usb storage device" 3 40
fi
done
}

error_node(){
echo ""
echo -e "You have one to many ${WHT}USB storage devices${FIN} connected."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please connect only ONE usb storage device" 3 40
fi
done
}

### EEPROM
update_eeprom(){
if [ -e /lib/firmware/raspberrypi/bootloader/stable/${PI_EEPROM}.bin ]; then
	:;
else
	if [[ `command -v deb-eeprom` ]]; then
		deb-eeprom -u;
		sleep 1s;
		deb-eeprom -U;
		sleep 1s;
	else
		echo "";
		echo -e "${YLW}Something went wrong${FIN}?";
		exit;	
	fi
fi
if [ -e /lib/firmware/raspberrypi/bootloader/stable/${PI_EEPROM}.bin ]; then
	:;
else
	echo "";
	echo -e "${YLW}Something went wrong${FIN}?";
	exit;
fi
sed -i 's/FIRMWARE_RELEASE_STATUS="default"/FIRMWARE_RELEASE_STATUS="stable"/g' /etc/default/rpi-eeprom-update
sed -i 's/FIRMWARE_RELEASE_STATUS="critical"/FIRMWARE_RELEASE_STATUS="stable"/g' /etc/default/rpi-eeprom-update
sed -i 's/FIRMWARE_RELEASE_STATUS="beta"/FIRMWARE_RELEASE_STATUS="stable"/g' /etc/default/rpi-eeprom-update
sudo rpi-eeprom-update -d -f /lib/firmware/raspberrypi/bootloader/stable/${PI_EEPROM}.bin
}

### EXT4 PARTITION
partition_ext4(){
partprobe ${USB}
sleep 4s
dd if=/dev/zero of=${USB} bs=512 count=1
truncate -s 2200MB ${USB}
fdisk ${USB} <<EOF
o
n
p
1
2048
524287
a
c
t
b
n
p
2
524288

p
w

EOF
partprobe ${USB}
echo 'y' | mkfs.vfat -n BOOT ${USB}1
echo 'y' | mkfs.ext4 -L ROOTFS ${USB}2
mkdir -p /mnt/p1 /mnt/p2
mount ${USB}1 /mnt/p1
mount ${USB}2 /mnt/p2
sync
umount /mnt/p2
mount -o defaults,noatime ${USB}2 /mnt/p2
bash growpart ${USB} 2 > /dev/null 2>&1
sleep 1s
resize2fs ${USB}2 > /dev/null 2>&1
sleep 1s
}

### F2FS PARTITION
partition_f2fs(){
partprobe ${USB}
sleep 4s
dd if=/dev/zero of=${USB} bs=512 count=1
truncate -s 2200MB ${USB}
fdisk ${USB} <<EOF
o
n
p
1
2048
524287
a
c
t
b
n
p
2
524288

p
w

EOF
partprobe ${USB}
echo 'y' | mkfs.vfat -n BOOT ${USB}1
echo 'y' | mkfs.f2fs -f -l ROOTFS ${USB}2
mkdir -p /mnt/p1 /mnt/p2
mount ${USB}1 /mnt/p1
mount ${USB}2 /mnt/p2
sync
umount /mnt/p2
bash resize.f2fs ${USB}2 > /dev/null 2>&1
mount -o rw,acl,active_logs=6,background_gc=on,user_xattr ${USB}2 /mnt/p2
sleep 1s
}

### BTRFS PARTITION
partition_btrfs(){
partprobe ${USB}
sleep 4s
dd if=/dev/zero of=${USB} bs=512 count=1
truncate -s 2200MB ${USB}
fdisk ${USB} <<EOF
o
n
p
1
2048
524287
a
c
t
b
n
p
2
524288

p
w

EOF
partprobe ${USB}
echo 'y' | mkfs.vfat -n BOOT ${USB}1
echo 'y' | mkfs.btrfs -f -L ROOTFS ${USB}2
mkdir -p /mnt/p1 /mnt/p2
mount ${USB}1 /mnt/p1
mount ${USB}2 /mnt/p2
btrfs subvolume create /mnt/p2/@
sync
umount /mnt/p2
mount -o compress=lzo,noatime,subvol=@ ${USB}2 /mnt/p2
bash growpart ${USB} 2 > /dev/null 2>&1
sleep 1s
btrfs filesystem resize max ${USB}2 > /dev/null 2>&1
sleep 1s
}

### RSYNC
transfer(){
cd /
cp -fdrP /boot/* /mnt/p1/
rsync -apvx --progress --stats --human-readable . /mnt/p2 > /dev/null 
}

transfer_to_usb(){
source /etc/opt/progressbar.txt
    enable_trapping
    setup_scroll_area
    for i in {0..100}
    do
        if [ $i = 0 ]; then
            block_progress_bar $i
        else
            transfer
            draw_progress_bar $i
        fi
    done
    destroy_scroll_area
}

### FETCH UUID
sleep 1s
partition_uuid(){
echo 'BOOT_UUID="' > boot1
blkid -o export -- "${USB}1" | sed -ne 's/^UUID=//p' > boot2
echo '"' > boot3
paste -d '\0' boot1 boot2 boot3  > /etc/opt/boot-id.txt
rm -f boot1 boot2 boot3

echo 'ROOT_UUID="' > root1
blkid -o export -- "${USB}2" | sed -ne 's/^UUID=//p' > root2
echo '"' > root3
paste -d '\0' root1 root2 root3  > /etc/opt/root-id.txt
rm -f root1 root2 root3

echo 'ROOT_PARTUUID="' > root1
blkid -o export -- "${USB}2" | sed -ne 's/^PARTUUID=//p' > root2
echo '"' > root3
paste -d '\0' root1 root2 root3  > /etc/opt/root-pid.txt
rm -f root1 root2 root3
}

### CMDLINE
ext4_cmdline(){
source /etc/opt/root-pid.txt
rm -f /mnt/p1/cmdline.txt
tee /mnt/p1/cmdline.txt <<EOF
console=serial0,115200 console=tty1 root=PARTUUID=${ROOT_PARTUUID} rootfstype=ext4 fsck.repair=yes logo.nologo net.ifnames=0 firmware_class.path=/lib/firmware/updates/brcm rootwait
EOF
}

f2fs_cmdline(){
source /etc/opt/root-pid.txt
rm -f /mnt/p1/cmdline.txt
tee /mnt/p1/cmdline.txt <<EOF
console=serial0,115200 console=tty1 root=PARTUUID=${ROOT_PARTUUID} rootfstype=f2fs fsck.repair=yes logo.nologo net.ifnames=0 firmware_class.path=/lib/firmware/updates/brcm rootwait
EOF
}

btrfs_cmdline(){
source /etc/opt/root-pid.txt
rm -f /mnt/p1/cmdline.txt
tee /mnt/p1/cmdline.txt <<EOF
console=serial0,115200 console=tty1 root=PARTUUID=${ROOT_PARTUUID} rootfstype=btrfs rootflags=subvol=@ fsck.repair=yes logo.nologo net.ifnames=0 firmware_class.path=/lib/firmware/updates/brcm rootwait
EOF
}

### EXTLINUX
ext4_extlinux(){
source /etc/opt/root-pid.txt
rm -f /mnt/p1/extlinux/extlinux.conf
tee /mnt/p1/extlinux/extlinux.conf <<EOF
label default
	kernel /Image
	append console=tty1 console=ttyS0,115200 console=both 8250.nr_uarts=1 rw root=PARTUUID=${ROOT_PARTUUID} rootfstype=ext4 fsck.repair=yes logo.nologo net.ifnames=0 cma=320M firmware_class.path=/lib/firmware/updates/brcm rootwait
EOF
}

f2fs_extlinux(){
source /etc/opt/root-pid.txt
rm -f /mnt/p1/extlinux/extlinux.conf
tee /mnt/p1/extlinux/extlinux.conf <<EOF
label default
	kernel /Image
	append console=tty1 console=ttyS0,115200 console=both 8250.nr_uarts=1 rw root=PARTUUID=${ROOT_PARTUUID} rootfstype=f2fs fsck.repair=yes logo.nologo net.ifnames=0 cma=320M firmware_class.path=/lib/firmware/updates/brcm rootwait
EOF
}

btrfs_extlinux(){
source /etc/opt/root-pid.txt
rm -f /mnt/p1/extlinux/extlinux.conf
tee /mnt/p1/extlinux/extlinux.conf <<EOF
label default
	kernel /Image
	append console=tty1 console=ttyS0,115200 console=both 8250.nr_uarts=1 rw root=PARTUUID=${ROOT_PARTUUID} rootfstype=btrfs rootflags=subvol=@ fsck.repair=yes logo.nologo net.ifnames=0 cma=320M firmware_class.path=/lib/firmware/updates/brcm rootwait
EOF
}

### FSTAB
ext4_fstab(){
source /etc/opt/boot-id.txt
source /etc/opt/root-id.txt
rm -f /mnt/p2/etc/fstab
tee /mnt/p2/etc/fstab <<EOF
UUID=${BOOT_UUID}	/boot		vfat    defaults 0 2
UUID=${ROOT_UUID}	/		ext4	defaults,noatime,nodiratime,commit=600,errors=remount-ro 0 1
tmpfs	/tmp		tmpfs	defaults,nosuid 0 0
EOF
}

f2fs_fstab(){
source /etc/opt/boot-id.txt
source /etc/opt/root-id.txt
rm -f /mnt/p2/etc/fstab
tee /mnt/p2/etc/fstab <<EOF
UUID=${BOOT_UUID}	/boot		vfat    defaults 0 2
UUID=${ROOT_UUID}	/		f2fs	rw,acl,active_logs=6,background_gc=on,user_xattr 0 0
tmpfs	/tmp		tmpfs	defaults,nosuid 0 0
EOF
}

btrfs_fstab(){
source /etc/opt/boot-id.txt
source /etc/opt/root-id.txt
rm -f /mnt/p2/etc/fstab
tee /mnt/p2/etc/fstab <<EOF
UUID=${BOOT_UUID}	/boot		vfat    defaults 0 2
UUID=${ROOT_UUID}	/		btrfs	defaults,compress=lzo,noatime,subvol=@ 0 1
tmpfs	/tmp		tmpfs	defaults,nosuid 0 0
EOF
}

### EXECUTION
run_ext4(){
run_as_root
internet_check
check_progressbar

if [ $ERROR ]; then
    error_node;
else 
    correct
fi

echo
confirm
echo
echo -e "${WHT}Updating eeprom${FIN} ..."
update_eeprom
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Partitioning USB${FIN} ..."
partition_ext4 > /dev/null 2>&1
echo -e "${WHT}Done${FIN}."

echo
echo -e "${YLW}Please be patient as the boot and root filesystem${FIN}"
echo -e "${YLW}are transferred over to the USB drive${FIN}."
transfer_to_usb
clear
sleep 1s

echo
echo -e "${WHT}Fetching UUID${FIN} ..."
partition_uuid
sleep 1s
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Creating new cmdline${FIN} ..."
if [[ `grep -w "bcm2711" "/etc/opt/soc.txt"` ]]; then
	ext4_cmdline;
fi
if [[ `grep -w "bcm2711" "/etc/opt/board.txt"` ]]; then
	ext4_extlinux;
fi
sleep 1s
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Creating fstab${FIN} ..."
ext4_fstab
sleep 1s
echo -e "${WHT}Done${FIN}."

echo 
echo -e "${WHT}Unmounting USB${FIN} ..."
rm -fdr /etc/opt/root-pid.txt /etc/opt/root-id.txt \
/etc/opt/boot-id.txt
rm -fdr /mnt/p2/mnt/*
umount /mnt/p2/boot > /dev/null 2>&1
umount /mnt/p2 > /dev/null 2>&1
umount /mnt/p1 > /dev/null 2>&1
rm -fdr /mnt/*
echo -e "${WHT}Done${FIN}."
echo
echo You may now power down and remove the sdcard.
}

run_f2fs(){
run_as_root
internet_check
if [[ `command -v mkfs.f2fs` ]]; then 
	:;
else
	apt update;
	apt install -y f2fs-tools;
fi
check_progressbar

if [ $ERROR ]; then
    error_node;
else 
    correct
fi

echo
confirm
echo
echo -e "${WHT}Updating eeprom${FIN} ..."
update_eeprom
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Partitioning USB${FIN} ..."
partition_f2fs > /dev/null 2>&1
echo -e "${WHT}Done${FIN}."

echo
echo -e "${YLW}Please be patient as the boot and root filesystem${FIN}"
echo -e "${YLW}are transferred over to the USB drive${FIN}."
transfer_to_usb
clear
sleep 1s

echo
echo -e "${WHT}Fetching UUID${FIN} ..."
partition_uuid
sleep 1s
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Creating new cmdline${FIN} ..."
if [[ `grep -w "bcm2711" "/etc/opt/soc.txt"` ]]; then
	f2fs_cmdline;
fi
if [[ `grep -w "bcm2711" "/etc/opt/board.txt"` ]]; then
	f2fs_extlinux;
fi
sleep 1s
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Creating fstab${FIN} ..."
f2fs_fstab
sleep 1s
echo -e "${WHT}Done${FIN}."

echo 
echo -e "${WHT}Unmounting USB${FIN} ..."
rm -fdr /etc/opt/root-pid.txt /etc/opt/root-id.txt \
/etc/opt/boot-id.txt
rm -fdr /mnt/p2/mnt/*
umount /mnt/p2/boot > /dev/null 2>&1
umount /mnt/p2 > /dev/null 2>&1
umount /mnt/p1 > /dev/null 2>&1
rm -fdr /mnt/*
echo -e "${WHT}Done${FIN}."
echo
echo You may now power down and remove the sdcard.
}

run_btrfs(){
run_as_root
internet_check
if [[ `command -v mkfs.btrfs` ]]; then
	:;
else
	apt update;
	apt install -y btrfs-progs;
fi
check_progressbar

if [ $ERROR ]; then
    error_node;
else 
    correct
fi

echo
confirm
echo
echo -e "${WHT}Updating eeprom${FIN} ..."
update_eeprom
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Partitioning USB${FIN} ..."
partition_btrfs > /dev/null 2>&1
echo -e "${WHT}Done${FIN}."

echo
echo -e "${YLW}Please be patient as the boot and root filesystem${FIN}"
echo -e "${YLW}are transferred over to the USB drive${FIN}."
transfer_to_usb
clear
sleep 1s

echo
echo -e "${WHT}Fetching UUID${FIN} ..."
partition_uuid
sleep 1s
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Creating new cmdline${FIN} ..."
if [[ `grep -w "bcm2711" "/etc/opt/soc.txt"` ]]; then
	btrfs_cmdline;
fi
if [[ `grep -w "bcm2711" "/etc/opt/board.txt"` ]]; then
	btrfs_extlinux;
fi
sleep 1s
echo -e "${WHT}Done${FIN}."

echo
echo -e "${WHT}Creating fstab${FIN} ..."
btrfs_fstab
sleep 1s
echo -e "${WHT}Done${FIN}."

echo 
echo -e "${WHT}Unmounting USB${FIN} ..."
rm -fdr /etc/opt/root-pid.txt /etc/opt/root-id.txt \
/etc/opt/boot-id.txt
rm -fdr /mnt/p2/mnt/*
umount /mnt/p2/boot > /dev/null 2>&1
umount /mnt/p2 > /dev/null 2>&1
umount /mnt/p1 > /dev/null 2>&1
rm -fdr /mnt/*
echo -e "${WHT}Done${FIN}."
echo
echo You may now power down and remove the sdcard.
}

echo -en "${WHT}"
options=("EXT4" "BTRFS" "F2FS" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "EXT4")
            run_ext4
	    break
            ;;
        "BTRFS")
            run_btrfs
	    break
            ;;
        "F2FS")
            run_f2fs
	    break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
echo -en "${FIN}"
